packages:
  - packages/*

catalogMode: prefer

catalog:
  "@anywidget/types": ^0.4.0
  "@observablehq/notebook-kit": ^2.1.8
  "@observablehq/parser": ^6.1.0
  "@shikijs/core": ^4.3.1
  "@shikijs/engine-javascript": ^4.3.1
  "@shikijs/langs": ^4.3.1
  "@shikijs/themes": ^4.3.1
  "@types/node": ^22.18.0
  es-module-lexer: ^2.3.0
  jsdom: 29.1.1
  typescript: ^6.0.3
  vite: npm:@voidzero-dev/vite-plus-core@0.2.4
  vite-plus: 0.2.4

minimumReleaseAge: 1440
minimumReleaseAgeStrict: true

overrides:
  vite: "catalog:"

peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"

allowBuilds:
  esbuild: true
