packages:
  - apps/*
  - packages/*

catalogMode: prefer

catalog:
  "@anywidget/types": ^0.4.0
  "@docusaurus/theme-mermaid": 3.10.2
  "@mermaid-js/layout-elk": 0.1.9
  "@observablehq/notebook-kit": ^2.1.9
  "@observablehq/parser": ^6.1.0
  "@observablehq/stdlib": ^5.8.8
  "@orama/plugin-docusaurus-v3": 3.1.18
  "@shikijs/core": ^4.3.1
  "@shikijs/engine-javascript": ^4.3.1
  "@shikijs/langs": ^4.3.1
  "@shikijs/themes": ^4.3.1
  "@types/node": ^22.20.1
  jsdom: 29.1.1
  typescript: ^6.0.3
  vite: npm:@voidzero-dev/vite-plus-core@0.2.4
  vite-plus: 0.2.4

minimumReleaseAge: 1440
minimumReleaseAgeStrict: true
minimumReleaseAgeExclude:
  - anywidget-bundle@0.0.1

overrides:
  vite: "catalog:"

peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"

allowBuilds:
  "@manzt/uv": true
  core-js: true
  esbuild: true
